### ISSUE TITLE
Rex fails to process dmidecode inventory

### ISSUE THREAD

**Issue by djzort** [RexOps/Rex#1385] opened 2020-07-23 06:05 UTC
Just run Rex against a Proxmox LXC container running linux

```
dean@cliffjumper:~/git/bf/rex-conf$ rex -H bf.fragfest.local install_bf
[2020-07-22 23:04:04] INFO - Running task install_bf on bf.fragfest.local
[2020-07-22 23:04:05] INFO - No lshal available
[2020-07-22 23:04:05] INFO - Got no cpu information from dmidecode. Falling back to /proc/cpuinfo
Use of uninitialized value $key in string eq at /home/dean/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/Rex/Inventory/Proc/Cpuinfo.pm line 37.
Use of uninitialized value $key in hash element at /home/dean/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/Rex/Inventory/Proc/Cpuinfo.pm line 43.
[2020-07-22 23:04:05] ERROR - Error executing task:
[2020-07-22 23:04:05] ERROR - Not an ARRAY reference at /home/dean/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/Rex/Inventory/DMIDecode/Section.pm line 81.

[2020-07-22 23:04:05] ERROR - 1 out of 1 task(s) failed:
[2020-07-22 23:04:05] ERROR - 	install_bf failed on bf.fragfest.local
[2020-07-22 23:04:05] ERROR - 		Not an ARRAY reference at /home/dean/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/Rex/Inventory/DMIDecode/Section.pm line 81.
```

FYI dmidecode does this
```

root@bf:~# dmidecode
# dmidecode 3.2
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
Scanning /dev/mem for entry point.
/dev/mem: No such file or directory
root@bf:~# 
```

**Comment by djzort** [comment] 2020-07-23 06:08
Swapping in this line seems to fix it

`  81    my @items        = ref $ref_to_items eq 'ARRAY' ? @{$ref_to_items} : ();            

But it may be better to sure up qualify_to_ref()                        `

**Comment by ferki** [comment] 2020-08-02 12:18
Thanks for the report @djzort! Unfortunately I have a hard time to understand the problem since it seems the issue template was ignored. What code did you run, and which Rex version did you use? I've recently rewritten many expressions in Rex to use `qualify_to_ref()`. Which file did you edit for the fix? Maybe an upgrade fixes it instead?

To have a clearer picture of what's happening, please edit the opening post of the issue to be based on the bug report template (or less ideally, perhaps open a new one replacing this).

**Comment by djzort** [comment] 2020-08-04 04:33
## Describe the bug

Rex crashes with the error above

## How to reproduce it

rex -H host.name whatever_thing

## Expected behavior

Rex runs

## Circumstances

 - Rex version: (R)?ex 1.12.0
 - Perl version: v5.26.3
 - OS running rex: Debian
 - OS managed by rex: Debian 10 as a proxmox lxc

**Comment by djzort** [comment] 2020-08-04 04:35
qualify_to_ref doesnt return an arrayref so it dies.

the root cause is that dmidecode doesnt return anything in an LXC

**Comment by ferki** [comment] 2020-08-04 14:15
Oh, I think I get it now, thanks!

If I understand correctly the failure is not directly related to Proxmox or LXC per se, but in general when `dmidecode` doesn't return anything useful, then Rex bails out with an error instead of trying to gracefully fall back. It's good to know as additional context, that inside LXC `dmidecode` is useless even as root..thanks!

And it fails in the `Rex::Inventory::DMIDecode::Section` module, it was just not visible at first glance due to the very long line in the OP. It might also worth to take a look at `Rex::Inventory::Proc::Cpuinfo` in this case, as it also complains about uninitialized values (but it's able to continue after that).

**Comment by ferki** [comment] 2020-08-04 14:20
@djzort: could you check what's the return code of the failing `dmidecode` command in your example inside LXC? That might be a good candidate to check for this scenario as early in the process as possible.

**Comment by djzort** [comment] 2020-08-05 05:44
root@bf:~# dmidecode
# dmidecode 3.2
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
Scanning /dev/mem for entry point.
/dev/mem: No such file or directory
root@bf:~# echo $?
1
root@bf:~#

**Comment by djzort** [comment] 2020-08-23 20:26
This seems to now be impacting me for physical servers.

```
dean@cliffjumper:~/git/bf/rex-conf$ rex -v
(R)?ex 1.12.1
```
I am trying to configured a new supermicro based server.

```
root@batou:~# dmidecode --version
3.2
root@batou:~# cat /etc/debian_version 
10.5
```

The `dmidecode` command works though, when run from shell as root.

**Comment by ferki** [comment] 2020-08-25 08:49
So finally I could reproduce it. The original example of `rex -H host.name whatever_thing` suggested that any remote rex task would be affected. I simply couldn't get the error to show up in my use cases, despite having the same rex and dmidecode versions.

Perhaps a proper code example with actual reproducible results would help understanding the next bug faster. The shortest I found to reproduce it is the following one-liner:

```
rex -e 'use Rex::Commands::Inventory; use DDP; my $inventory = inventory(); p $inventory;'
```

Now that I have actual code to play with, I believe the problem has at least two different aspects.

First, when `dmidecode` is being run without proper privileges (~non-root), then rex complains about all the cpuinfo messages as seen in the original report. It's able to continue, but then dies with the `Not an ARRAY reference` error later.

Second, when `dmidecode` is run as root, then it dies with the `Not an ARRAY reference` message.

I suspect there might have been some change in the dmidecode output/behavior, so it would probably be helpful to add sample output to the test suite from dmidecode 3.x as well (we now only have samples from 2.10 and 2.11). On top of that, rex should either continue with a warning, or die with a more meaningful error message (depending on the severity of the underlying issue).

**Comment by ferki** [comment] 2020-08-25 17:20
So according to "manual git bisect", the dmidecode bug was indeed introduced on 36c515d1e1675f0685a103b700beee60eda2b3ba, and the problem is that it doesn't properly populate section properties anymore.

The proper fix has to be applied to the `has` function, where the references are currently mishandled, this it fails to populate the expected properties for the various dmidecode sections.

For extra safety, the rest of the commit has to be reviewed and/or further tested for correctness. Or perhaps the commit has to be reverted.

**Comment by ferki** [comment] 2020-08-25 21:11
Ha, this proved to be a tricky one so far. On further investigation, I think it might have been just a "typo", as the following diff fixes dmidecode too:

```diff
-  my @items        = @{$ref_to_items};
+  my @items        = @{ *{$ref_to_items} };
```

Looks like I forgot to use the typeglob with this instance of replacements for some reason. I'll double check the rest of the problematic commit and see if other places need further tests or similar fixes. If I can't solve it by going forward, I'll revert the buggy commit before the next release to restore the old code pathes.

**Comment by djzort** [comment] 2020-08-25 21:20
Some high magic fun there.

**Comment by ferki** [comment] 2020-08-25 21:25
> Some high magic fun there.

It was even higher magic "fun" while the [original code](https://github.com/RexOps/Rex/commit/36c515d1e1675f0685a103b700beee60eda2b3ba#diff-84cf6fa7d6d5f9ba58d7f0c5ce49e899L44-L57) used `no strict 'refs';` ... ;)

**Comment by djzort** [comment] 2020-08-26 00:15
As inventory() returns a hashref it has to go and do everything every time, even though in my case i mainly only want to know a few basic things.

Food for thought:

If Rex::Commands::Inventory might return an object then all the methods could lazy load (or preload if asked)

**Comment by ferki** [comment] 2020-08-26 06:35
That's right, I agree there are newer/better/faster/etc. ways of doing things, but that's part of the story of taking over maintenance of a ~10 years old established project (especially with a strong promise of backwards compatibility).

To speed repeated steps up, Rex could use the already built-in caching for inventory as well. Changing the returned data format of an interface that was established over 9 years ago sounds more complicated. Ideally there would be a dmidecode parsing module on CPAN we could just reuse, but I'm not yet aware of any that would be a good fit.

While Rex would probably implement one or more of these ideas at a later point in time, I consider the above out of scope for _this_ issue. What I plan to do in the current context is the following:

- I see the main issue to be a regression in dmidecode handling that was introduced recently, and can be fixed with adding 5 characters. For extra safety I'll double-check the rest of the commit (including test coverage) that introduced this regression.
- The side-issue is about warnings displayed while parsing cpuinfo as a fallback option if dmidecode data is unavailable. That is caused by empty lines in `/proc/cpuinfo` content. So I also expect a relatively straightforward fix with `next if $line =~ qr{^$};` or similar (and perhaps adding a nicer warning output + tests).

**Comment by ferki** [comment] 2020-08-26 15:51
I believe #1410 fixes both of the issues seen in the original report. I've added some extra tests which exercises the problematic code pathes. It works on my end, plus in all Travis CI builds (Linux, Windows, Mac OS X).

@djzort: could you give that branch a try too, please? I can wait a bit with the merging if you are able to give further feedback.

**Comment by djzort** [comment] 2020-08-26 19:45
> That's right, I agree there are newer/better/faster/etc. ways of doing things, but that's part of the story of taking over maintenance of a ~10 years old established project (especially with a strong promise of backwards compatibility).

I wouldn't suggest changing the behaviour of inventory() for that reason, but also because i think that the use case of "give me everything in a hash" is valid.

**Comment by ferki** [comment] 2020-08-26 20:20
> I wouldn't suggest changing the behaviour of inventory() for that reason, but also because i think that the use case of "give me everything in a hash" is valid.

I'm not sure I'm following this part of the conversation correctly. If there's a strong need to change the inventory format, I'd like to make sure I understand the reasons thoroughly, so let's discuss that on IRC first (or in a different feature request). If there's no such pressure, then it's all good :)

> Parse::DMIDecode and DMI::Decode look about the same and a similar vintage. I couldn't speak to whats missing in either.

Thanks for the suggestions, I was looking at those earlier. Both have their last release in 2007, have inactive maintainers, and their test results make me uncomfortable (one of them has a single failing result and nothing else, the other has good test coverage, but with test failures overlapping with the Rex support matrix). DMI::Decode is also actually not Perl, but inlined C code.

I'm sure a more thorough evaluation will be made at the time when we are actually looking at replacing the core implementation. It's also an option to try and take over maintenance of these modules, but it feels like a lot of effort - maybe it's even more economical to split out the current implementation or start something new.

> > could you give that branch a try too, please? I can wait a bit with the merging if you are able to give further feedback.
> 
> I would be glad too.

Awesome! Fingers crossed! :crossed_fingers:

**Comment by djzort** [comment] 2020-08-27 05:00
Fixes it for me

**Comment by ferki** [comment] 2020-08-27 07:01
> Fixes it for me

Great! Thanks again for the report and the testing, as well as for the ideas along the way!

**Closed** 2020-08-27 07:01 UTC
Labels: bug

**Comment by djzort** [comment] 2020-08-27 07:40
Thanks for fixing a nasty bug
