### ISSUE TITLE
Allow to custom CMDB modules provide their how get_value method

### ISSUE THREAD

**Issue by gonzalo-radio** [RexOps/Rex#1379] opened 2020-07-22 09:05 UTC
## User story

**As** a contributor
**I would like to** use my own get_value when is using a custom CMDB module
**so I can** access to my data as like i want

## Describe the solution you'd like

I already have a solution implemented and the pull request is coming next to this issue. But in mi solution the `cmdb` method check if the `CMDB_PROVIDER` has a `get_value` method and use his own in case not.

## Describe alternatives you've considered

i don't have one, but i am open to other solutions :)

## Additional context

Maybe this is possible to do in another way, if this is true, please, let me know.

Sorry for mi English, i am working on it.

**Comment by ferki** [comment] 2020-07-31 14:07
Hmm, I'm not sure I understand why would we need to introduce this new interface. Why would someone need this new method? What is the scenario that this interface solves and the current one doesn't?

Perhaps as a first step, the user story here can be reworded to be more specific about _what_ is the problem we try to solve, and not about _how_ we try to solve it. And maybe some examples could help understanding the case as well.

Once we got the problem clearly described, we can write a test for the proposed solution and implement the change.

@gonzalo-radio: feel free to ping us on IRC too for further help and discussion!

**Comment by gonzalo-radio** [comment] 2020-07-31 15:15
> Perhaps as a first step, the user story here can be reworded to be more specific about what is the problem we try to solve, and not about how we try to solve it. And maybe some examples could help understanding the case as well.

Ok, seems right to do that :)

At the company i work for, we have an internal service to provide information about the inventory of machines and his configuration variables.
This information is provided with the structure of Ansible inventory in JSON. I supose you know how is it but if not its something like this:

```js
{
  "_meta": {
    "hostvars": {
      "host1": {}
    }
  },
  "group1": {
    "hosts": {},
    "vars": {}
  }
}
```

As we will like to use Rex more, i made a custom CMDB module to query this information.
But i found myself with a hassle, with `get cmdb('some value')` only can get the top key of hash, never the inner keys.

Because of this my CMDB module allows do something like this: `get cmdb('/path/to/the/key/i/want')` and will get the value of:

```js
{
  "path": {
    "to": {
      "the": {
        "key": {
          "i": {
            "want": "value"
          }
        }
      }
    }
  }
}
```


Maybe i am wrong and there is a way to do something like this with the actual state of  CMDB base module.

> @gonzalo-radio: feel free to ping us on IRC too for further help and discussion!

Im there already, but only as a reader. I don't have the courage to establish a chat communication in English because i have to think more about how to say something than the thing i want to say. :sweat: 

I hope my English is good enough to explain myself and help you to understand me.
Thank you for your time :)

**Comment by ferki** [comment] 2020-07-31 18:36
> But i found myself with a hassle, with `get cmdb('some value')` only can get the top key of hash, never the inner keys.
> 
> Because of this my CMDB module allows do something like this: `get cmdb('/path/to/the/key/i/want')` and will get the value [...]

Ah, I think I see it, thanks for the clarification! I think we should be able to write a more precise user story about getting values from nested CMDB structures.

> Maybe i am wrong and there is a way to do something like this with the actual state of CMDB base module.

I don't think so, and the last I checked, there were no standard notation or generic module for this kind of access. For JSON, there is [`JSON::Path`](https://metacpan.org/pod/JSON::Path), which might be used to write a `Rex::CMDB::JSON::Path` module. But I don't think I'm aware about a more generic approach (for example for YAML).

> > @gonzalo-radio: feel free to ping us on IRC too for further help and discussion!
> 
> Im there already, but only as a reader. I don't have the courage to establish a chat communication in English because i have to think more about how to say something than the thing i want to say. 

Of course, no need to use IRC if you are uncomfortable with that.

> I hope my English is good enough to explain myself and help you to understand me.

Don't worry, I think your English seems good enough! :hugs:

> Thank you for your time :)

Thank _you_ for taking the extra effort to write us in English!

**Comment by gonzalo-radio** [comment] 2020-08-03 06:04
> But I don't think I'm aware about a more generic approach (for example for YAML).
> > >
Maybe we can use [ETL-Yertl](https://metacpan.org/release/ETL-Yertl) since they provide a standard notation for `yaml`, `json`, `sql` and `csv`.

**Comment by gonzalo-radio** [comment] 2020-08-03 06:24
i forgot to add this:

```perl

```

**Comment by ferki** [comment] 2020-08-03 10:59
Is there anything preventing to put that splitting logic directly into the `get` method of the custom CMDB module? That way it wouldn't need to introduce a new API:

Something like:

```perl
sub get {
    my $self, $path = @_;

    my $hash  = get_cmdb_data_from_somewhere();
    my @parts = split '/', $path;

    for my $part (@parts) {
        $hash = $hash->{$part} if ref $hash eq 'HASH';
    }

    my $value = ref $hash eq 'ARRAY' ? c($hash) : $hash;
    return Rex::Value->new( value => $value );
}
```

**Comment by gonzalo-radio** [comment] 2020-08-03 15:19
That was my first try, but the `Rex::CMDB::cmdb` don't send the item requested to the get of `$CMDB_PROVIDER`:

https://github.com/RexOps/Rex/blob/1a7bc5322f1ed873d3fb5d917c9b00e7595bd54c/lib/Rex/CMDB.pm#L162

and get the value itself:

https://github.com/RexOps/Rex/blob/1a7bc5322f1ed873d3fb5d917c9b00e7595bd54c/lib/Rex/CMDB.pm#L166-L168

So, i don't think it is possible to do what it want without changing the `Rex::CMDB::cmdb` itself or providing a mechanims to get the value.

Let me know if i'm wrong about this.

**Comment by ferki** [comment] 2020-08-03 15:41
You're right, thanks for the debugging and explanation! Now I understand your situation and requirements better, and I also understand your code in the PR better.

So in other words it's about supporting multi-level CMDB data structures. One way is introducing a new API for that like you did :+1: 

If there's a way to do it with keeping the current API, I think I would prefer that though. Maybe it is also possible to (optionally?) pass the requested item to the CMDB providers, so they can apply further logic to obtain the value (and then probably push down caching to the CMDB providers too).

I think the `undef` is passed instead of the item only because we want to retrieve the whole CMDB data structure in order to cache it for the next query. If we pass the item instead of `undef`, the caching has to be done in the providers if they need it, but they gain a lot of flexibility (which sounds like a good thing).

It's a very interesting topic, I have to think more about how it would be best to approach this!

**Comment by gonzalo-radio** [comment] 2020-08-04 20:39
Hello! 

Sorry the delay, i don't been have time until right now. 

So, the only thing be need to add support to the multi-level CMDB data structures is something like this on `Rex::CMDB::cmdb`:

```perl
sub cmdb {                                                  
  my ( $item, $server ) = @_;                               
  $server ||= connection->server;                           
                                                            
  return if !cmdb_active();                                 
                                                            
  my $value;                                                
  my $cache     = Rex::get_cache();                         
  my $cache_key = "cmdb/$CMDB_PROVIDER/$server";            
                                                            
  if ( $cache->valid($cache_key) ) {                        
    $value = $cache->get($cache_key);                       
  }                                                         
  else {                                                    
    $value = $CMDB_PROVIDER->get( undef, $server ) || undef;
    $cache->set( $cache_key, $value );                      
  }                                                         
                                                            
  for my $part ( split '/', $item ) {                       
      $value = $value->{$part} if ref $value eq 'HASH';     
  }                                                         
                                                            
  if ( defined $value ) {                                   
    return Rex::Value->new( value => $value );              
  }                                                         
  else {                                                    
    Rex::Logger::debug("CMDB - no item ($item) found");     
    return;                                                 
  }                                                         
}                                                           
```
or maybe 
```perl
  if ( $item && (my @parts = split( '/', $item )) ) {    
    for my $part (@parts) {                              
        $value = $value->{$part} if ref $value eq 'HASH';
    }                                                    
  }                                                      
  elsif ( $item ) {                                      
    $value = $value->{$item};                            
  }                                                      
```

what do you think?
which option do you like more?

**Comment by ferki** [comment] 2020-08-06 15:26
Hmm, that might work for this specific CMDB provider, or similar ones which also use `/` as separator. But still does the splitting on the top level, so it wouldn't work for different notation (or each possible future notation has to be added to Rex core as well).

What I have in mind is to let the CMDB provider (for example your own custom module) to do the splitting if they need splitting. For that, I think we should pass them `$item` instead of `undef` in the line you showed earlier:

https://github.com/RexOps/Rex/blob/1a7bc5322f1ed873d3fb5d917c9b00e7595bd54c/lib/Rex/CMDB.pm#L162

Otherwise they don't know what to split.

I expect that would conflict with the caching behavior, though. Currently we retrieve the whole CMDB data structure from the provider (when we pass `undef` first) and cache that on first access. And then any further access will use the cached version. If  we pass `$item`, we would only cache the subset of the CMDB data structure, so the next query might have to reread the whole source again. That is potentially not just slow, but dangerous in case the CMDB data changes between the queries.

So for that to work, maybe we can try to "ask for the whole first, cache it, then ask for `$item`", but I think it might be best to let the CMDB providers handle the cache too.

I think these two changes has the potential to break backwards compatibility, so they would require more test cases and probably a new feature flag too.

**Comment by ferki** [comment] 2020-10-10 17:07
@gonzalo-radio: I finally had the capacity to do some debugging today, and I believe this is a regression bug introduced on #1240. Previously the CMDB providers received `$item`, but not anymore. That should definitely happen so this bug will be fixed. That should allow CMDB providers again to handle item retrieval on their own (for example parsing `/`-separated CMDB keys in your case).

How that effects the caching behavior is a different story, and has to be further explored. I think there's a way to still cache the CMDB results per server, but if not, the caching decisions should be pushed down to the CMDB provider layer. I believe both approaches have pros and cons, and the details still have to be figured out.

**Closed** 2020-10-30 22:14 UTC
Labels: bug
