### ISSUE TITLE
The after hook should run even if we fail to connect the the host

### ISSUE THREAD

**Issue by mbroadhead** [RexOps/Rex#794] opened 2015-09-15 18:49 UTC
In the [API documentation](http://www.rexify.org/api/Rex/Commands.pm.html#after-task-sub-), it implies that the "after" hook will execute even if we fail to connect to the server:

```perl
after mytask => sub {
  my ($server, $failed, $cli_args) = @_;
  if($failed) { say "Connection to $server failed."; }

  run "vzctl stop vm$server";
 };
```

However, when I run a simple test, it does not execute the after hook if it fails to connect:
```perl
use Rex -base;

task "foo" => sub {
  say "task foo";
};
after "foo" => sub {
  say "after foo";
};
1;
```

```
$ rex -v
(R)?ex 1.3.3

$ rex -H dkfjdkfj foo
[2015-09-15 11:39:38] INFO - Running task foo on dkfjdkfj
[2015-09-15 11:39:38] INFO - Connecting to dkfjdkfj:22 (mitch)
[2015-09-15 11:39:40] WARN - Can't connect to dkfjdkfj (unable to establish master SSH connection: master process exited unexpectedly)
[2015-09-15 11:39:40] WARN - Error running task/batch: Wrong username/password or wrong key on dkfjdkfj. at /Users/mitch/perl5/perlbrew/perls/perl-5.20.2/lib/site_perl/5.20.2/Rex/TaskList/Base.pm line 309.

[2015-09-15 11:39:40] INFO - Exiting Rex...
[2015-09-15 11:39:40] INFO - Cleaning up...
```

As you can see, the above execution did not output "after foo" as I was expecting.

**Comment by kablamo** [comment] 2015-09-15 21:00
I agree that it should run the after hook.  This was a problem for me too.  I would love to see a pr for this.  

In the short term, I just discovered there is an undocumented "exit_hook" in Rex::CLI which might help you depending on what you need.  Just be aware that kind of undocumented internal stuff could change or disappear.  To solve this, I wrote my own version of `run()` called `runt()` and handle errors in there.   I needed my own version of `run()` anyway because I need streaming output (like tail -f).  

Both those suggestions suck.  Might be easier to just create a pr to fix this.

**Comment by mbroadhead** [comment] 2015-09-15 22:19
@kablamo I actually created a whole new hook called "after_connect_failure" on a [branch](https://github.com/mbroadhead/Rex/commit/4e890e04410bbe41f6b67c252e96bbce5a241ab4) before I found out that the "after" hook was supposed to be used in this way. I imagine I can just use the logic I did there to call the "after" hook instead.  I'll look into the "exit_hook" in Rex::CLI too. Thanks for the suggestion.

**Comment by ferki** [comment] 2015-09-23 18:43
@mbroadhead: is is possible that the [`after_task_finished`](http://www.rexify.org/api/Rex/Commands.pm.html#after_task_finished-task-sub-) hook solves your problem? I tried your example locally, could reproduce it, then I replaced the `after` hook with `after_task_finished`, and I think it worked as you described your expectations (i.e. it ran despite the SSH connection failure).

Of course, the documentation should be clearer on the details.

**Comment by mbroadhead** [comment] 2015-09-25 18:16
@ferki The [after_task_finished](http://www.rexify.org/api/Rex/Commands.pm.html#after_task_finished-task-sub-) hook only runs once after the task has been executed on all hosts, right? Also, nothing tracks which hosts failed to connect, so that information is not available inside the after_task_finished hook. The benefit of the [after](http://www.rexify.org/api/Rex/Commands.pm.html#after-task-sub-) hook is that it runs once per host. If it did run after a connection failure, you could use the after hook to append to a list of hosts that failed to connect. My use case is that I want to take a local action if a host fails to connect, like appending the host to connection_failures.txt. Then I could use after_task_finished to generate a report of connection failures.

```perl
use Rex -base;

task connect_check => sub {
  say run "uptime";
};
after connect_check => sub {
  my ($server, $failed, $cli_args) = @_;
  if($failed) {
    my $fh = file_append("connect_failures.txt");
    $fh->write($server);
  }
};
after_task_finished connect_check => sub {
  my $fh = file_read("connect_failures.txt");
  say "We could not connect to the following servers:";
  say $fh->read_all;
  $fh->close;
};
```

**Comment by kablamo** [comment] 2015-09-25 18:40
@mbroadhead You might also be interested in this pr which summarizes success/failure at the end of a rex run: https://github.com/RexOps/Rex/pull/697

Its related, but doesn't really solve this issue imo.  I want to be able to take action immediately when a task fails.  For example I want to log the failure to hipchat/slack/irc/whatever.

**Comment by mbroadhead** [comment] 2015-09-25 18:51
@kablamo #697 is an excellent PR that I'd like to see implemented. It would be interesting to have that summary available to the user in some kind of variable available in the <code>after_task_finished</code> hook. The user could then use the report in many different ways. In my case, send the report via email.

But as you note, #697 PR doesn't solve this issue. Being able to take immediate action on connection failures via the <code>after</code> hook would be extremely useful.

**Comment by krimdomu** [comment] 2015-10-08 07:04
yes, this is indeed a bug in the code and not in the documentation.
the after hook should also run when the connection fails.

**Comment by krimdomu** [comment] 2015-12-18 21:54
@mbroadhead the patch to run the after hook even when the connection failed is now merged. So i'm closing this issue.

**Closed by krimdomu** 2015-12-18 21:54 UTC
Labels: bug

**Comment by mbroadhead** [comment] 2016-02-28 19:37
Hey guys, thanks for the fix.
