### ISSUE TITLE
rexify --bundle doesn't work on debian wheezy

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#916] opened 2016-01-27 09:53 UTC
The problem is, Net::OpenSSH and Net::SFTP::Foreign are tool old and doesn't have the files we list in `rexify` data section.

**Comment by bechtoldt** [comment] 2016-01-27 10:04
please notice that on debian wheezy the tool ``readelf`` is available as ``eu-readelf``:

https://packages.debian.org/wheezy/amd64/elfutils/filelist

**Comment by bechtoldt** [comment] 2016-01-27 10:24
PS: https://github.com/bechtoldt/rex-docker/blob/debian-wheezy-latest/Dockerfile contains all steps to get ``rexify --bundle`` working on debian:wheezy.

**Comment by ferki** [comment] 2020-08-19 20:59
According to the [Release table](https://en.wikipedia.org/wiki/Debian_version_history#Release_table) on Wikipedia, Debian Wheezy is not supported anymore, so I'm closing this bug.

Newer versions of Debian contain newer versions of Net::OpenSSH and Net::SFTP::Foreign as well, so I'm not sure if the issue is still valid. In case it's still a problem for anyone reading this, please open a new bug report.

**Closed by ferki** 2020-08-19 20:59 UTC
Labels: bug
