### ISSUE TITLE
Unicode characters are not displayed correctly

### ISSUE THREAD

**Issue by zhumengu** [RexOps/Rex#1480] opened 2021-03-06 10:47 UTC
## Describe the bug

The default setting is `LC_ ALL=C ` execute command, cannot specify system locale manually

## How to reproduce it

Shortest code example that demonstrates the bug:

```perl
task "run_command", make {
  say run "nmcli connection show -a";
};
```

## Expected behavior
```
NAME        UUID                                  TYPE      DEVICE
有线连接 1  9451c57c-8e9d-3e02-9ac2-fae1b412c8b1  ethernet  enp4s0
```

### actually
```
NAME        UUID                                  TYPE      DEVICE
？？？？？  9451c57c-8e9d-3e02-9ac2-fae1b412c8b1  ethernet  enp4s0
```

## Circumstances

 - Rex version: (R)?ex 1.13.1
 - Perl version: v5.32.1
 - OS running rex: Manjaro Linux
 - OS managed by Manjaro Linux
 - How rex was installed: cpanm

**Comment by ferki** [comment] 2021-03-06 11:10
Thanks for the report to provide additional context for #1479!

This feels like a duplicate of #1230 - could you cross-check it, please?

As [commented there](https://github.com/RexOps/Rex/issues/1230#issuecomment-534253558), it should be possible to specify `no_locales => TRUE` with `run` commands to use whatever locale is set on the remote. Optionally, `env => { LC_ALL => 'set_some_other_locale' };` can also be added to set locale through the environment (and it needs documentation apparently).

Perhaps that's already useful as a workaround for your use case, and there's also further discussion about how to solve it in a more generic way.

**Comment by zhumengu** [comment] 2021-03-06 11:46
Thank you for your reply, you are very awesome

**Comment by zhumengu** [comment] 2021-03-06 12:11
Rex::Interface::Exec::Local.pm "locale" is hard-coded, manually specifying it will not work

```
[2021-03-06 20:00:03] DEBUG - Executing network_info
[2021-03-06 20:00:03] DEBUG - Executing: **export LC_ALL='zh_CN.UTF-8'**;  export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/pkg/bin:/usr/pkg/sbin ; **LC_ALL=C** nmcli conn show -a
[2021-03-06 20:00:03] DEBUG - NAME        UUID                                  TYPE      DEVICE
???? 1  9451c57c-8e9d-3e02-9ac2-fae1b412c8b1  ethernet  enp4s0

NAME        UUID                                  TYPE      DEVICE ???? 1  9451c57c-8e9d-3e02-9ac2-fae1b412c8b1  ethernet  enp4s0
```

The environment variable specified by the run method is useless to take effect

**Comment by ferki** [comment] 2021-03-06 13:01
Hmm, having inconsistent behavior between `Rex::Interface::Exec::Local` and `Rex::Interface::Exec::SSH` definitely sounds like a bug (but it is a different one).

If I understand correctly: for local runs the `env` is respected, but the `no_locales` isn't.

I have to think more about how it would be best to address these. If I understand correctly, the PR #1479 is trying to solve this from the side of locale options, but it's incomplete (no tests, local run needs to work on Windows too, etc.). I believe it might be easier/faster to mark this as duplicate of #1230 (due to the original locale part), and solve the `no_locales` bug separately (which would remove the inconsistency).

**Closed** 2021-03-07 02:58 UTC
Labels: triage needed

**Comment by ferki** [comment] 2021-03-07 08:54
@zhumengu: last night I worked on a patch for the difference between `Rex::Interface::Exec::Local` and `Rex::Interface::Exec::SSH` in the `local_exec_sell` branch, which fixes `no_locales` for `run` command on local runs. It might already help your use case, and I'd like to include that in the next release.

I'll create two new issues later:
- one about fixing this inconsistency
- one about fixing the locale settings globally
