### ISSUE TITLE
Inconsistent behavior between "packaged" and "unpackaged" task modules

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1303] opened 2020-04-19 08:42 UTC
I keep bumping into differences of behavior between a task module that has `package Blah::Blah` and one that doesn't.

Example:

Given this Rexfile:
```
use Rex -feature => ['1.4'];
use Blah;

our $Server;

before_task_start 'ALL' => sub {
  $Server = 'the server';
};
```
And this task module:
```
#package Blah;
use Rex -base;
no strict;

task blah => sub {
  no warnings 'once';
  print $Server . "\n";
};

1;
```

and `rex blah` is run on the command line, it works and `the server` is output. However, if `#package blah` is uncommented out and rex Blah.blah is run, nothing is output.

**Comment by ferki** [comment] 2020-04-19 09:43
> I keep bumping into differences of behavior between a task module that has package Blah::Blah and one that doesn't.

Well, using perl modules without `package` were never a design goal, so this use case is definitely new, so it probably has many pitfalls and breakages. I'm still trying to understand the exact use case behind trying to make "packageless modules" work, and I find it quite strange.

If a task warrants using a new namespace so it is being split into its own module, then `package` is the perl way to put a namespace on it. If someone doesn't need the namespace, then why split it off into a new module?

I think what might be useful is to start a new issue describing the _actual_ problem that needs to be solved to describe the use, define the expected behaviour with many examples _and_ written tests, and _then_ choose a solution based on possible alternatives.

Since this use case is definitely not supported as of now, and this issue doesn't have any actionable items, I'll close it for now. If "packageless namespaces" gets supported in the future, it would definitely need a more comprehensive design/analysis first.

**Closed by ferki** 2020-04-19 09:43 UTC

**Comment by ferki** [comment] 2020-04-19 14:23
Few points after trying to debug this for a while now:

1. Having to use `no strict` and `no warnings` should be warning signs that something unusual is being attempted.

1. To share variables between tasks (including task hooks), check out [Rex::Shared::Var](https://metacpan.org/pod/Rex::Shared::Var).

1. The variables, subroutines, etc. defined in a `Rexfile` are registered under the `Rex::CLI` namespace, so their fully qualified form is e.g. `$Rex::CLI::Server`.

That being said, the `print` in `Blah.pm` can try to print `$Rex::CLI::Server` for more clarity, and that would help getting rid of `no strict` as well (that I assume was put there because of a `Global symbol "$Server" requires explicit package name (did you forget to declare "my $Server"?)` error).

Sadly, I couldn't figure out yet why the `no warnings 'once'` had to be used.

But that leaves us with the following `Blah.pm` at this point:

```perl
#package Blah;
use Rex -base;

task blah => sub {
  print $Rex::CLI::Server . "\n";
};

1;
```

If we uncomment and activate `package Blah`, then rex starts to complain about `Can't add before_task_start (?^:.*), as it is not yet defined`. That means, the task named `blah` never gets a hook registered with it to be run before the task. Which in turn means, there's no value assignment takes place for `$Server` in the `Rex::CLI` namespace. And if I'm correct, that's exactly the background of #1302.

**Comment by sdondley** [comment] 2020-04-19 15:13
Apologies. I had some cruft left over in the code. The `no warning` is there quiet the complaints of the vim syntastic plugin.

I forgot to mention that I have patch from #1302 applied in addition to this patch.

Thanks for letting me know the full name of the `$Server` variable. I couldn't figure it out.

**Comment by sdondley** [comment] 2020-04-19 15:29
OK, someone mentioned using a "packageless" task module as a workaround to not having to use fully qualified task names on the command line in freenode chat. I thought this was a supported feature.

For me, the use case is just better organization and grouping of related functions into distinct filed. This can probably be accomplished in other ways (maybe with `do`?). Although packageless task modules do make it easier to type in tasks.

At any rate, thanks for the input and feedback.

**Comment by sdondley** [comment] 2020-04-19 15:43
WRT to https://metacpan.org/pod/Rex::Shared::Var, I did attempt to get this working last night when I was noodling with this. I was not successful in getting it working.

**Comment by ferki** [comment] 2020-04-19 15:54
I believe the use case there was to be able to use simpler (that is shorter) task names.

IIRC a few days ago there were mentions on IRC about too long tasknames if the module hierarchy is deep, like `Company:Service:Subsystem:configure`.

If the task name `configure` is put into a file called `lib/Rex/Company/Service/Subsystem.pm`, normally the file has `package Rex::Company::Service::Subsystem;` line on top to indicate the namespace (that is, "Rex code is just Perl code).

Note that `Rex::`/`Rex:` prefix has already been removed from the fully qualified task name.

The proposal there was to "let's omit the `package` from the top of the module", because then Perl don't see it as a namespace, so Rex would also not add the prefix to the task name.

This is a hack, and looks like it breaks in unexpected ways, well, as expected.

For the "my task names are too long" problem, there might some workarounds:
  - have a wrapper package with a short name for each package that has a long name, for example `C:S:S` for `Company:Service:Subsystem`
  - have some wrapper tasks at the top-level which delegate calling of the task defined at deeper levels, e.g. task `configure_service` just dispatches `needs Rex::Company::Service::Subsystem 'configure'`. This probably can be done dynamically as well, that is writing code that figures out what other task it needs to call.

And as a proper solution at least the following comes to mind:
  - make hidden namespace prefixes configurable (e.g. not just hide `Rex::`, but also more, like `Rex::Company::Service::Subsystem`)
  - optionally introduce a short notation for a common prefix, like other popular Perl project do (e.g. `+Service::Subsystem` would already imply `Rex::Company` as a prefix)
  - implement a feature that would allow calling tasks by their shortest unique names (e.g. if there's only one task called `configure`, then calling `rex configure` would figure out which one it is, even if it is buried deep inside `Rex::Company::Service::Subsystem`)

**Comment by ferki** [comment] 2020-04-19 16:02
> WRT to https://metacpan.org/pod/Rex::Shared::Var, I did attempt to get this working last night when I was noodling with this. I was not successful in getting it working.

Without seeing your code, it's hard to tell why, but the initial example had many issues already, so I wouldn't wonder too much if other features got broken too.

You can take a look for [shared var examples in the docs](https://metacpan.org/pod/Rex::Shared::Var), and in some tests, like `t/hooks.t`.
