### ISSUE TITLE
Rex::Commands::Sync

### ISSUE THREAD

**Issue by davehodg** [RexOps/Rex#1428] opened 2020-09-14 11:25 UTC
## User story

**As** a sysadmin
**I would like to** have more options on Rex::Commands::Sync
**so I can** back up more efficiently

## Describe the solution you'd like 

I just got a backup Rexfile working. Two things jumped out at me. I'd like compression and ignoring of broken links.

**Comment by ferki** [comment] 2020-09-14 13:01
Hmm, interesting idea, thanks for sharing, @davehodg!

At first glance, I'm not entirely convinced to push Rex core towards being a backup solution in itself or out-of-the-box. There are plenty of excellent projects available having backup as their core competency. Especially if backup efficiency is the goal, perhaps it's worth considering a purpose-made solution to handle all the domain-specific aspects of backup requirements (compression, encryption, deduplication, transfer, restore, etc.).

That being said, it does sound something that can be built by using Rex: relying on Rex::Commands::Sync to handle the transport part, and using custom code around the `sync` call to handle the compression bits. That makes it sound like a good idea for an extension module (`Rex::Commands::Sync::Compressed`, or even `Rex::Commands::Backup`?). If someone's interested in that, it could even be pushed towards having full rsync-like functionality without using rsync itself.

(History bits: `Rex::Commands::Sync` was written to provide basic file syncing functionality on platforms where `Rex::Commands::Rsync` can not be supported. I'd say developing a much more complete rsync replacement inside Rex core would be out of scope currently, but such an effort sounds like a logical continuation down that path. It could live outside core, and later Rex could either depend on that module, or it might be merged into core - whichever has the most benefits at that point)

Compression alone is an interesting aspect, as it may get quite complicated to support long-term in a responsible manner. There are many different compression methods, each of those having a multitude of options, and on top of that, compression might apply at three different stages at least:

- before sending the content from the source side
- during transfer (so the transport layer, like SSH or HTTP(S) need to be configured (mostly?) outside Rex)
- after receiving the content on the target

Based on that, I'd prefer to leave the choices of "when to compress" and "how to compress" to be made in the user's codebase during implementation instead of implementing and maintaining a generic support for all these in core.

If there's a bug about link handling currently, we might need to fix that, or perhaps we could add an option to deescalate that into a warning.

**Comment by davehodg** [comment] 2020-09-14 13:52
Well clearly this is something I could just as easily do with rsync, but I'm learning Rex, so hey :)

**Comment by ferki** [comment] 2020-09-14 14:12
> Well clearly this is something I could just as easily do with rsync, but I'm learning Rex, so hey :)

It is still an interesting idea, so I hope these are useful pointers above for everyone wondering about the topic at a later point :)

If rsync is an option, I'd definitely recommend using that. `Rex::Commands::Sync` was born because Windows users of Rex normally don't have the `rsync` binary, nor the `Expect` module available as a dependency for `Rex::Commands::Rsync` to work.

If broken links cause trouble with `Rex::Commands::Sync`, let's look into that with greater detail on a bug report. Without further context, I can imagine that the expected behavior in such a situation is to fail and let the admin investigate. But even then, we usually can improve Rex to provide a more useful error message, or to let it fail gracefully under some circumstances.

It sounds like we pretty much covered the various aspects here, so I'm closing this feature request for now. If I'm wrong, keep commenting and/or reopen :)

**Closed by ferki** 2020-09-14 14:12 UTC
Labels: feature request

**Comment by davehodg** [comment] 2020-09-14 14:18
The broken link was a php.ini pointing into a different wordpress install where it didn't exist.
