### ISSUE TITLE
Lots of Perl warnings on simple (but probably incorrect) -H parameters

### ISSUE THREAD

**Issue by szabgab** [RexOps/Rex#1483] opened 2021-03-22 09:37 UTC
Probably I am using the host feature incorrectly, but IMHO there should not be Perl-level warnings and why is it trying to access s0  anyway?

```
$ rex -v
(R)?ex 1.13.3
```

```
rex -u root -H 's[78]' -e 'run(q{hostnane})'

Use of uninitialized value in numeric eq (==) at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1808.
Use of uninitialized value in numeric eq (==) at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1808.
Use of uninitialized value $to in numeric le (<=) at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1813.
Use of uninitialized value $from in numeric le (<=) at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1813.
Use of uninitialized value $strict_length in concatenation (.) or string at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1814.
Use of uninitialized value $from in sprintf at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1815.
Use of uninitialized value $to in numeric le (<=) at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1813.
Use of uninitialized value in numeric eq (==) at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1808.
Use of uninitialized value in numeric eq (==) at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1808.
Use of uninitialized value $to in numeric le (<=) at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1813.
Use of uninitialized value $from in numeric le (<=) at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1813.
Use of uninitialized value $strict_length in concatenation (.) or string at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1814.
Use of uninitialized value $from in sprintf at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1815.
Use of uninitialized value $to in numeric le (<=) at /home/gabor/perl5/lib/perl5/Rex/Commands.pm line 1813.
[2021-03-22 11:36:28] INFO - Running task eval-line on s0
[2021-03-22 11:36:29] WARN - Can't authenticate against s0 (unable to establish master SSH connection: master process exited unexpectedly)
[2021-03-22 11:36:29] ERROR - 1 out of 1 task(s) failed:
[2021-03-22 11:36:29] ERROR - 	eval-line failed on s0
[2021-03-22 11:36:29] ERROR - 		Couldn't authenticate against s0. It may be caused by one or more of:
[2021-03-22 11:36:29] ERROR - 		 - wrong username, password, key or passphrase
[2021-03-22 11:36:29] ERROR - 		 - changed remote host key
[2021-03-22 11:36:29] ERROR - 		 - root is not permitted to login over SSH
[2021-03-22 11:36:29] ERROR - 		 at /home/gabor/perl5/lib/perl5/Rex/TaskList/Base.pm line 343.
```

**Comment by ferki** [comment] 2021-04-25 10:44
Thanks for your report!

Next time please use the bug report template, or at least provide an explanation why it has to be ignored for the given case, as described in the [Contributing guide](https://github.com/RexOps/Rex/blob/master/CONTRIBUTING.md) (specifically in the section about [GitHub issues and pull requests](https://github.com/RexOps/Rex/blob/master/CONTRIBUTING.md#github-issues-and-pull-requests)).

That being said, the problem here seems to be that `s[78]` is not a valid hostgroup expression. According to [`group` docs](https://metacpan.org/pod/Rex::Commands#group) the valid ones are `\d+..\d+` (range), `\d+..\d+/\d+` (range with step), `\d+,\d+,\d+` (list), or a combination of those.

This does sound like a bug, which probably can be fixed by checking the hostgroup expression (or its expanded result) for validity, and `die()`ing with a more informative error message. It would be nice to convert the opening post to the standard bug template.

ps.: it can also be reproduced by printing the verbose task list with `rex -H 's[78]' -Tv`.

**Comment by szabgab** [comment] 2021-04-25 10:55
IMHO Rex should never print any Perl-level warnings.

**Comment by ferki** [comment] 2021-04-25 11:01
> IMHO Rex should never print any Perl-level warnings.

Yes, and I believe that's what #477 is about.

**Closed** 2021-07-08 20:19 UTC
Labels: bug
