### ISSUE TITLE
problem with rsync command and wildcards

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#1106] opened 2016-10-19 09:40 UTC
There is a problem reported via IRC that wildcards and the rsync command doesn't work.

I think this is a problem with the function that try to calculate the path.

Example: https://people.debian.org/~christoph/POC.txz

**Comment by ferki** [comment] 2016-10-19 09:56
FTR: #1075 seems at least related, if not duplicate.

**Comment by mestia** [comment] 2018-02-08 10:09
See the same problem with rex 1.6.
It also complains about 

> Redundant argument in sprintf at /usr/share/perl5/Rex/Commands/Rsync.pm line 238

**Comment by ferki** [comment] 2020-06-25 15:53
> See the same problem with rex 1.6.
> It also complains about
> 
> > Redundant argument in sprintf at /usr/share/perl5/Rex/Commands/Rsync.pm line 238

@mestia: seems like that was a different problem, and it was resolved on #1297 (and a similar one on #1237).

**Comment by ferki** [comment] 2020-06-25 15:53
Closing as duplicate of #1075.

**Closed by ferki** 2020-06-25 15:53 UTC
Labels: bug
